name: port_scanner
description: A starting point for Dart libraries or applications.
version: 0.0.1
repository: https://github.com/mfazrinizar/port_scanner

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  win32: ^5.10.0
  ffi: ^2.1.3
  # path: ^1.8.0

dev_dependencies:
  pedantic: ^1.11.1
  lints: ^5.0.0
  test: ^1.24.0
